version: "3.9" 
services:
  event-database:
    container_name: event-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: api
      POSTGRES_DB: api
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  event-scheduler:
    build: .
    depends_on:
      event-database:
        condition: service_healthy
    ports:
      - 4100:4000    

networks:
  default:
    # Use a custom driver
    name: event-scheduler-net
